const fs = require('fs');
const path = require('path');
const assert = require('assert/strict');
const { pathToFileURL } = require('url');
const { chromium } = require('C:/Users/ewert/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');

(async () => {
  const root = path.resolve(__dirname, '..');
  const file = path.join(root, '[EN] CV - Ewerton Gomes de Lucena 2026 - Interactive.html');
  const browser = await chromium.launch({headless:true, executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1050}, reducedMotion:'reduce'});
    const errors=[];
    const externalRequests=[];
    page.on('pageerror', e=>errors.push(e.message));
    page.on('request', request=>{if(/^https?:/.test(request.url()))externalRequests.push(request.url());});
    await page.goto(pathToFileURL(file).href);
    await page.evaluate(()=>document.fonts.ready);
    assert.equal(await page.locator('h1').count(),1);
    assert.equal(await page.locator('.job').count(),8);
    assert.equal(await page.locator('.education-item').count(),5);
    assert.equal(await page.locator('.skill-tags li').count(),12);
    assert.equal(await page.locator('.certificate').count(),22);
    assert.deepEqual(await page.locator('main>section').evaluateAll(elements=>elements.map(el=>el.id)),['objective','experience','education','skills','credentials','languages','interests']);
    assert.equal(await page.locator('a[href="mailto:ewerton.lucena@hotmail.com"]').count(),1);
    assert.equal(await page.locator('a[href="tel:+5521997541185"]').count(),1);
    assert.equal(await page.locator('table').count(),0);
    await page.screenshot({path:path.join(__dirname,'preview-desktop.png')});
    await page.locator('[data-filter="microsoft"]').click();
    assert.equal(await page.locator('.certificate:visible').count(),7);
    await page.locator('#credential-search').fill('Purview');
    assert.equal(await page.locator('.certificate:visible').count(),2);
    await page.locator('#credential-search').fill('no-matching-credential');
    assert(await page.locator('#empty-state').isVisible());
    await page.locator('#reset-search').click();
    assert.equal(await page.locator('.certificate:visible').count(),22);
    await page.locator('[data-filter="other"]').click();
    assert.equal(await page.locator('.certificate:visible').count(),15);
    await page.locator('[data-filter="all"]').click();
    await page.locator('#toggle-details').click();
    assert.equal(await page.locator('.responsibilities[open]').count(),0);
    await page.locator('#toggle-details').click();
    assert.equal(await page.locator('.responsibilities[open]').count(),7);
    await page.locator('#theme-toggle').click();
    assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
    assert.equal(await page.locator('#theme-toggle').getAttribute('aria-label'),'Switch to dark theme');
    await page.evaluate(()=>window.scrollTo(0,0));
    await page.screenshot({path:path.join(__dirname,'preview-light.png')});
    await page.locator('#theme-toggle').click();
    await page.locator('.nav a[href="#skills"]').click();
    const position=await page.locator('#skills').boundingBox();
    assert(position.y>=75&&position.y<160);
    await page.evaluate(()=>window.scrollTo(0,0));
    for(const width of [1440,1024,768,390,320]) {
      await page.setViewportSize({width,height:900});
      const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
      assert(overflow.scroll<=overflow.width+1,JSON.stringify(overflow));
    }
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.join(__dirname,'preview-mobile.png')});
    await page.locator('#credential-search').fill('SC-401');
    assert.equal(await page.locator('.certificate:visible').count(),1);
    await page.locator('#toggle-details').click();
    assert.equal(await page.locator('.responsibilities[open]').count(),0);
    await page.pdf({path:path.join(__dirname,'print-check.pdf'),format:'A4',preferCSSPageSize:true,printBackground:true});
    assert.equal(await page.locator('.responsibilities[open]').count(),0,'Print must restore the prior disclosure state');
    await page.locator('#credential-search').fill('');
    await page.locator('#toggle-details').click();
    await page.setViewportSize({width:1440,height:1050});
    await page.evaluate(()=>window.scrollTo(0,0));
    await page.screenshot({path:path.join(__dirname,'preview-desktop.png')});
    const contrast=await page.evaluate(()=>{
      const rgb=color=>color.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});
      const lum=color=>{const v=rgb(color);return .2126*v[0]+.7152*v[1]+.0722*v[2];};
      const body=getComputedStyle(document.body);
      const check=color=>{const a=lum(color),b=lum(body.backgroundColor);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);};
      return {body:check(body.color),muted:check(getComputedStyle(document.querySelector('.hero-caption')).color),accent:check(getComputedStyle(document.querySelector('.eyebrow')).color)};
    });
    Object.values(contrast).forEach(value=>assert(value>=4.5));
    assert.equal(await page.locator('.orbit').evaluate(el=>getComputedStyle(el).animationName),'none');
    assert.deepEqual(errors,[]);
    assert.deepEqual(externalRequests,[],'The HTML must not fetch any external assets');
    const noScript=await browser.newPage({javaScriptEnabled:false});
    await noScript.goto(pathToFileURL(file).href);
    assert.equal(await noScript.locator('.certificate:visible').count(),22);
    assert.equal(await noScript.locator('.responsibilities[open]').count(),7);
    await noScript.close();
    await page.keyboard.press('Tab');
    const report={checks:'passed',roles:8,education:5,skills:12,credentials:22,widths:[1440,1024,768,390,320],externalRequests:0,consoleErrors:0,contrast,contentWithoutJavaScript:'complete',print:'A4, all content despite collapsed roles and credential filter'};
    fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify(report,null,2));
    console.log(JSON.stringify(report));
  } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exit(1);});
